/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.numberToWords.NumberToWordsID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public String testFunction() {
        var number = new NumberToWordsID();
        return number.convertNumberToWords(111L);
    }

    public static void main(String[] args) {
        System.out.println(new App().testFunction());
    }
}
